version: "3"
services:
  redis:
    container_name: redisserver
    image: redis
    ports:
        - 6379:6379
    networks:
      - webnet
  db:
    container_name: databaseserver
    image: postgres
    ports:
        - 5432:5432
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: passn
      POSTGRES_USER: usern
      POSTGRES_DB: newdb
  web:
    container_name: webserver
    image: node
    build: .
    command: bash -c "sleep 10 && npm run migrate && npm run dev"
    volumes:
      - ".:/usr/src/app"
    working_dir: "/usr/src/app"
    depends_on:
      - "db"
    ports:
      - 5000:3000
    environment:
      POSTGRES_URI: postgres://usern:passn@192.168.99.100:5432/newdb
      DB_PASSWORD: passn
      SERVER_PORT: 3000
      DB_POST: 5432
      DB_USER: usern
      DB_NAME: newdb
      DB_HOST: db
      REDIS_HOST: '192.168.99.100'
      REDIS_PORT: 6379
networks:
  webnet:
