version: "3"
services: 
    redis:
        image: redis:alpine
    postgres:
        image: postgres
        ports:                                                                                                                                                                  
            - 5432:5432 
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: fixtures
    web:
        build: .
        ports:
            - 80:3000
        volumes:
            - .:/usr/src/app
        depends_on:
            - postgres
            - redis

            